version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/
hooks:
  BeforeInstall:
    - location: .megalisk/setup.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: .megalisk/run.sh
      timeout: 300
      runas: root
