services:
  nginx-webserver:
    image: nginx:1.15-alpine
    restart: unless-stopped
    ports:
      - "${PORT:-80}:80"
      - "${SSL_PORT:-443}:443"
    networks:
      - obelisk

networks:
  obelisk:
